#include <stdio.h>
#include <windows.h>

int main ()
{
printf ("                                ./oyhhhdhhyyss+/-`                                                  \n");
printf ("                              .+hhddddhhhyhhhysso+:`                                                \n");
printf ("                            `+hhhhdddddddhhhhhhyso+/-`                                              \n");
printf ("                           :yhddhdddddhhhhhhdhhysoo+::.                                             \n");
printf ("                          +yhhhhhhhhhdhhhhyhdhyysoss+/:-                                            \n");
printf ("                         /syydhyhhhyydhyyyhyhdhhhyyyoo+/-                                           \n");
printf ("                        `yhdydhyyhhysyhhyhhdhhhddhhhyoo+/`                                          \n");
printf ("                        :ddddddhhhhhhh/yhyhhddhhddhdhyso+-                                          \n");
printf ("                        sddddsdhhhhhhh/:oyhhhhddhhhddhyss/                                          \n");
printf ("                       `hdhdh/hhhhhyyhs--/oyhhhhdddhdhhhy+                                          \n");
printf ("                       :ohhys/ohhhhhosh:.--+syhhhhhdddhhh+                                          \n");
printf ("                       /-hho-/-ooyso:./:/+oo/-:syhyyhddhhs-`                                        \n");
printf ("                       +/yy+./o+:..```.osmNmys.:yh+:yhddhy/:-                                       \n");
printf ("                       ossys/osdy.``````.sss/..-yh/-ydhhhys-`-                                      \n");
printf ("                       +o+yyy:-os-```````.--....yy+shdddhyso`+-                                     \n");
printf ("                      `/hhdyhs.--.````````....`-ssyhhhdddhys+s.                                     \n");
printf ("                      ..-hmdhh/....```````````.+soyhhdmddhyo+s`                                     \n");
printf ("                      +: :ddhhho:...````````.:oyy+:shmmmdyo/:`                                      \n");
printf ("                      .+/:/hhhhhhs/.......:osyyyy+-+/yosoo:.`                                       \n");
printf ("                           yhhyshho```````.-+soo/-:+/syys+/o.                                       \n");
printf ("                           hdyhhho` ``````-.``.``..-+/yy+-/:.                                       \n");
printf ("                          `ddyydd: ``````.--``````.`:hmd:.--                                        \n");
printf ("                          :ddyhdd-`````..-.`.`````..odmm+.                                          \n");
printf ("                          sddhmdd:.``````.``..`````/ddmms.`                                         \n");
printf ("                         :/shdddd/--..`.```.:``````ydddmy. `                                        \n");
printf ("                        `+`ohdhddo--.-.``.`-:`````+hddddy.``                                        \n");
printf ("                        /. ysyhddy::-```.`./.````:hddhhds-``                                        \n");
printf ("                       `o .h:sdds:.`````.`-/````-hdddhhd+:` .                                       \n");
printf ("                       -s /y`odds``...`.`.::```-ydhdhhdh/-` -                                       \n");
printf ("                       -y`s/ sdoh/.-.`.`.:/-..-yy+ddhhhy:.  ..                                      \n");
printf ("                        o:s` sh:so-...``-:/-..oo-sddhdh+.   ```                                     \n");
printf ("                        .ss`.yo:o+.-.``..::-.-+-.dmhdhs:`   ` `                                     \n");
printf ("                         +s./ho:oo-:```..::--o/--dmddh+`    `` `                                    \n");
printf ("                         oy/ydh+oy:.``.`---:-ys--smmdy+.``  `.  `                                   \n");
printf ("                         syoddds/h+ `-...:.::sdo:+hmhss...``...``                                   \n");
printf ("                         yhhdddh/s.`-.`.-:.`-/hmhssds-s/........``                                  \n");
printf ("                         ydssdddo+.--.-`:::.`.:sdmhyo:y+-...``...``                                 \n");
printf ("                         +dhsosdy.----``::-:.``.:ymhsshs````.`....``                                \n");
printf ("                         `odh/-dh.-:-```::..-.``.:mddhyo``.-``.-...``                               \n");
printf ("                           -y:odh--``...-:.``--``.yddhyo-..```----..```                             \n");
printf ("                           `//hdh. `..`.`--````..`/dhhhso-``````-----``                             \n");
printf ("                           -+hhhh:`--``.-`--`````.-hdhhy/o-````.-.`..-``                            \n");
printf ("                           /yhhhh+-:```.:.`.-`````+yhdhd+:+-......```````                           \n");
printf ("                          /oohhhhy-````-:-``.-```-d+hdddy.-/.....`````````                          \n");
printf ("                         -/-yhddho ``..-:--```..`sm:ydddy-o.....``````.`..                          \n");
printf ("                        `-`+hydho```.----.-.```.:dd:+dddoyo.```..------.`..                         \n");
printf ("                        -`.shhy+`  -``.--``..```ody:+ddhdo``..`````...``````                        \n");
printf ("                        -+.ohhho/-`.-`.-`````.``sdo.ohyh/``````.`````````````                       \n");
printf ("                         /o:yhdh/-:/---:-.``````/hs.yy+-.----..``...``````````.``                   \n");
printf ("                          `+oyyhhs+h+/:--:--.----ohyy-``````.....``......```````.                   \n");

printf ("                                                                                                    \n");
printf ("                                        `.----.``                                                   \n");
printf ("                                    `-/oyyyyyyssso+/.                                               \n");
printf ("                                 `.:oyyssoooosysyyhhho-                                             \n");
printf ("                               `./shddhddhyo//oyysshddyo`                                           \n");
printf ("                              `-+osyyhysyssss+shhssydhyds`                                          \n");
printf ("                             `:/++ooooooso+oshddhyyhhdhdd/                                          \n");
printf ("                             /yy+oyo//soyhhddddddhyyhddddy`                                         \n");
printf ("                            `yddddddddddmmdmddddhhdhhdddmd-                                         \n");
printf ("                            :dmddhsdmmmdhddhdddddddddhhhdh/                                         \n");
printf ("                            /dmmmo-yddddyyhyshhhdddhmdysss+--.                                      \n");
printf ("                            /dmmm/-/sysys++oosyhyhhhhhsyhhhsoh.                                     \n");
printf ("                            /dmdd+/sso:-:-..:+hy+hyyh+/syydyhy-                                     \n");
printf ("                           .+sddd+/+s+```````.//:yyyh+:shhmdd/:.                                    \n");
printf ("                          .o//hhhs--:-........--:shyyyyddddmhso-                                    \n");
printf ("                          `:-ohdddo--....````...:+dhoyddyyhs++ss`                                   \n");
printf ("                            `shooys+.``````.```.+oydsssys+o+:/o+-```                                \n");
printf ("                             /o..++:::```````:+:/odhoooo++oo+ooo/:-::.                              \n");
printf ("                             `-.-+/::.``.````-s+/syss++++oso/+yo///++/`                             \n");
printf ("                              .:+o+++```....-`++ssooo++++oso+oo/oyssoo/`                            \n");
printf ("                              .++o++:---:-:--:yhyooso+///+oo/:.`.+hso+/                             \n");
printf ("                             `..+:.----/:-:::-/h+oss+oooooo:.   ``sho/.                             \n");
printf ("                            .` `:`-...-s-./.+..:/+ss++++++-.`  `.`.hhs/``                           \n");
printf ("                            - `-`````.-s/...```.//h+/://:...````.``odhyo:...`                       \n");
printf ("                            ``-`.````.-s/...`.`.+:+-`.::..--.`` ....sso+++ooo+:`                    \n");
printf ("                              .....--:/:---....-:/-/-:/--.`..`  --`.//:.`..-shhs`                   \n");
printf ("                              :...-:://.:-::---.-:--o/-.....`  .:--`./:/-`  odmN-                   \n");
printf ("                             `+:..---:/.:://::--`..:-s/---.   `/:.` `:/+hs::hddy`                   \n");
printf ("                           `...------//-/::--.-:-``::/s:....``:/..   .-+yhhddd+`                    \n");
printf ("                           ````-:-.-o/:.:/--..-o/.`.+::o...` -+-.` ```  .ydddh+.                    \n");
printf ("                           ```.-..-/s:ss://--.--..`.::./..` .+/-.``..```sdd/`:sy+`                  \n");
printf ("                         ` ` `...-/-/ho`-://-......-.`--```./+...``..``-smo    :ys.                 \n");
printf ("                            `...--::sd+`.////:-....:.``-...-+:...```````/ys`    -yy.                \n");
printf ("                        `  ``...-::/yoy``::///-....-` `-...+/......``   `-sso/-..+d+                \n");
printf ("                        ` ````.--.-oy.-`-::///:-.......-../+-.........`  `:shhhhhhmd:`              \n");
printf ("                         ```..--.`.:h. `:::///+:-.....```-+/.............`..`-/sdmddddo-`           \n");
printf ("                       `--..--.`  -.y/:-////o+/:--..... .++:............-...``-oyo+yhohds:`         \n");
printf ("                    `:syhhhyhhysooo+yo+ossyyhsoo/......`:++-----...---.-..```-s+.  /y:`/hy+.        \n");
printf ("                   `ohhhhhddmdhyhyhhhdddddddddddh+/:--:/o++////+++/:-.---:.` ``   `s/.- .yso`       \n");
printf ("                   +hhhhhhddmyhyyyyhhdddhhhhhhhhhhhhddhyo+/+++ooossss-```.--.``  .s+` -  .ss-       \n");
printf ("          `..`     hhhhhdddmdyhyyyhhdddddhhhhhhhhhhdddddho+oosossyyys:..``..-..`-s/`.-`  `sy.       \n");
printf ("         `+///:`  .ddddddmmmdhhyyhhdmmmmdddddhhhhhhhhddddsyo+++oooy:..`````:....s/--.   `oh/        \n");
printf ("         `++::::. -mmmmmmmmmddhhhddddddmmmmmmdddddddddddmhhs/+/o+s+```````.-``.`- ``   .os:  `      \n");
printf ("          :++/:-:.`+dmmmmmmmdmdddddddhhhhddddmmmmmmmdddmmmmh+ossos+........`  `-```  `:+-`  `.      \n");
printf ("          `:::/++:``-ohmmmmdmmmmmmdddhhhhhhhhhddmmmmmmmmmmmmhyhooo+......` `-  ..::..+.  `..-`      \n");
printf ("          ````..-`````.:oyhddddmmmmmddddhhhhhhhhdddmmmNmmmmmmddsoss.-o/:`  `:` ``-/+y+:::-.`        \n");

printf ("                                                                                                    \n");
printf ("                                                                                                    \n");
printf ("                                            .:/++ooo+/:-`                                           \n");
printf ("                                        -+syhhhhhyyyyyysso+-`                                       \n");
printf ("                                     `-oyhhhddhyssyysysssssss+.                                     \n");
printf ("                                    `:ohdysssssyhyssssyyysssso+.                                    \n");
printf ("                                  `./+ssosooossohyhsoooyhdsooo+-.`                                  \n");
printf ("                                 .-++o++soooohoohyyhhsssshdy//+-:/                                  \n");
printf ("                                 ./++s+ooooosdsshhyyhhs+oosdo/oo++-                                 \n");
printf ("                               `.//+y++o+sssohsyhdsosyyyoooyhoosooo                                 \n");
printf ("                               .oyssmooyoyysoyoyydh+sdhdddhhhhyyyyh.                                \n");
printf ("                               /hhyhdhhdyhhhhhhhh/yhdmhdhdmmdddhhdd/                                \n");
printf ("                              .ydhhh/hhhdhhhhhhhd/:ohdddhhdmmmmdddmy                                \n");
printf ("                              /mmddy/yddhhhhhshhho/++shdddddddmmmmmm:.                              \n");
printf ("                             `hmmmmhshNds++/+//odNNdysyddddmdddmmmmm/o/                             \n");
printf ("                             /ddNddms:os-```````:+sy::sdmmddmmmNmmddsh-                             \n");
printf ("                            `oddmdhmm+/:.````````-:/::dmmmydNNNNNNmmm:                              \n");
printf ("                            .oh.odymNd:-.`````````.--odmmmdNMNNMNNNNy                               \n");
printf ("                             :h+odmhNNo.````````````-dmmmNMNMMMMMMmo`                               \n");
printf ("                              .+ydmmmNNy:.`````````.omNNmmNMNMMMNh.                                 \n");
printf ("                                 +dmNNNNms.``````-/+hdNmo.//odmmhy-`                                \n");
printf ("                               `-syhmmms/` ``.:////s+mm/.  `dmNdsso/                                \n");
printf ("                              `soohmNNmmd.    `////hyms  `./yydmdys+.                               \n");
printf ("                             `oyddmmmhhmm+`    /:/+hNh+---.````:Nmyss-                              \n");
printf ("                              /ddmmy:`++dmdo:-/:/ohdmo::-    ```oNNdNds.                            \n");
printf ("                            `+ohyh/.``o-smy:/:::oh:dh//-      ``:NNmNmdh+`                          \n");
printf ("                           -hhhyh:`-`.++hy-``..-o-/do+/``     .:/Nmmmmdhho-                         \n");
printf ("                          +mmddd:../`+oy+.``  ``/od/so:`   `.-/:/mNmmdddho.:.                       \n");
printf ("                         +mddmd+``://ss/...````.:ds+oo/.``-:///-/dmNmmdddy+`..                      \n");
printf ("                       ..h++:-/+osyhyo//.:/+-   -ssooo++/++++//+:+yhmmddhhs/``                      \n");
printf ("                      .://..``::/+:+`-:o++/.-` :yyhshyoo+++/+++///yyhmmdhyys/                       \n");
printf ("                      .+hd+/:://+oo+///hh/:`  `o/ooyy++s+o++//+++symddmmdyyyh.                      \n");
printf ("                     .+hddooydyso::+-./dd``.--:+.:+oo///:so+++ossymmdhhdmmhhy/                      \n");
printf ("                   ./hhdmhoyyhy/.-.:+/ydh-`..+//::/ooo///oo+oshs+hmmdhyhhdmdhy.                     \n");
printf ("                 ./+ssyo++/+/:..//---:+sy/--/.`-``:hhmyo:/yo.hdyhddmmhyyyhhddhs                     \n");
printf ("               .:+osshyo+o//--/+o:--:/:--...`  .:./yhdy+so+. sdo/dshmddsoososdd:                    \n");
printf ("             `.///+/yhhdms-//+:` ``-.` ```  `./os``::/++/+.  -dy.hsshhhdyso+:/yy`                   \n");
printf ("             .::oss.hyhdNo/-/`   `.`  ```.-:--::o-`.://oo//:-.od.s::o/oyhdhs+/+o/.`                 \n");
printf ("             `/+shy:dhhdNyy-` ````  `.-+ys/.  ``-::/oo+-````.:/ss+o ./.:oyddhssooo+:`               \n");
printf ("              `/ohysddhdmN/.`````.-/+shdhs+:.```:+ooo:-       `-+yy/-`-``:ohhysyyyyhso-`            \n");
printf ("               `/sosyddddm``.-::+syssyhmdhyyyo:..+s/+:     ``..:/++++:`-` `:syo+oossyhhy:`          \n");
printf ("                `+++syhdhd` /os`/ddddddmmmmmmmmysyy+do``.--::///////://`-`   /hs++ooosyydy:`        \n");
printf ("                 `o/+yhhddh/o/o/-+shdmmdyyysoooosydyy+:////:////////://:.`.  `hhyo+++oshhhds`       \n");
printf ("                  s-.oohdhys+/s+//+oydhs/+oosyhdddhyo/++/++/+++++/////:/-...  syhs.///:oydddy/`     \n");
printf ("                 ./ ..-o/-`   /oosyhmyys+:dhhhysosoo+//+++/+++++//////::/- /  :/+/  `+/-:shdmmy.    \n");
printf ("                  .:-``       `-+yyyhdhys+os/:/+oo+/:://+++++++++++///:/:+ o  -+/-   .shsoyyhmmy    \n");
printf ("                  `.          .+yo+osys++///...-+++---//++++++++++++///+oo:o  `o:.    :hmmhyyhd/    \n");
printf ("                 ``         .:+s/:://o/::++:-...-/+/---+/++++++yyossssso:.//-` //.    :hmmdh/hy-    \n");
printf ("         ```.`` ``        `-//:.`-::/:.``.-/+:--../+---//++++ooossoooos/::+osys/o.   `ymmdddsmh/    \n");
printf ("       .--``````````````.:/:... `--`-.    `-/o+::-://--:++oooo++++oossoo++/:+ydd+/. `ydddddhddh:    \n");
printf ("        .::::--.-...--:::-` `.  `-.`-`     `.+o++/-/++//+++///+++sssso+::-....:s` `.yy+hddddhs.     \n");
printf ("      `-/::::///::---..-`   ` ``..``.`       :++--:/++o++++++osssys+/:::-.``````...s--hddhdh:       \n");


printf ("                                               `  ````..:++++o+::::-.```  `                         \n");
printf ("                                               `  `.:/+osossysssssooo+/-`` `                        \n");
printf ("                                          ` `````:+oossyyyyyyyhyyyysssoo+.                          \n");
printf ("                                            ```./ossooshhhhhhhhhhyyyyysss+```                       \n");
printf ("                                              `/ossyhhhhhhhhhhddhhhyyyyso+:```                      \n");
printf ("                                          ` `-syyoshhhyyyhyyyhhhhhhyyysssss-```                     \n");
printf ("                                            -yhyyddyyossyyyyyyyyyyyy+syyysso.```                    \n");
printf ("                                           `yhydddhhsoyyyyhysosyyyyyhoyyyyss-```````                \n");
printf ("                                          `/hhddhhysoddddddhyyyyyhyyhhsyyyss:```````                \n");
printf ("                                      `   .yhdhhy+sosddhdddysyooyhhhyyhssyys:.``````                \n");
printf ("                                      ` ``+ddhyy/o++shhshhhso+:/shdyyyhhsyys:..`````                \n");
printf ("                                 ```   ``+hdhyy+o:/:ossosyy++-`/-sdyyyydhyys:..``   `               \n");
printf ("                                   ` ``.+/yyyso+:`--+++++o+-/``./-yyyyydhysy-..``   `               \n");
printf ("                                   `  .o/.oyoso+//+:--:--:-.-`` ./+ssyyhyyss:-.``   `               \n");
printf ("                                     `/o``:yos/.`:yy/ `` ``-/+++/:osssyhyyys/--``   `               \n");
printf ("                                 ` ``.s: `:y+s/-`-/:-`    ``./syy/osssyyysyso/-`` ``                \n");
printf ("                                 `  `.y/ `+yoss/....```  ````-----osss+yyosss+:`````                \n");
printf ("                                   ```/o-.sysyyy+```` ` ` ```....+ssssoysssss+-`````                \n");
printf ("                                  ``` `:///yyyhyy/.   ```  `````-ssssysosssss+. ````                \n");
printf ("                                    `` /..os/sssyys/.````` ``.-:ossssysssssoo:` `   `               \n");
printf ("                                   ````./os::+:+sy/://:-.---::/+yyysooso+ho:o-``    `               \n");
printf ("                                 ````.++--:``.-:oy//////:::/+++syyy+--+soss./.      `               \n");
printf ("                                  `-++-``.````-:os/shs:/:/+:/+/hyyo:-..-/os//```    `               \n");
printf ("                         ``    ``.+o:```.` ```-/ys/+s/++ooo..-/yso:-.````.-//```   ``               \n");
printf ("                         `` ``` .so.`..-.`````-/yo/os//oo:/:.:syy/.``````...:-`` ``                 \n");
printf ("                           ``` `.so/+o++/:--. ./yo++o++++//--:yy+.``` ``````-+.```                  \n");
printf ("                            ````-+++/++o++/-:`-sy+/:-::+/:/--oho.    `` ````.:+.                    \n");
printf ("                         ` ```..:///:-::///-:-o/s+/:./::/+:-/hy- `  ``  ````.-:+`                   \n");
printf ("                         ` ``````.:/:--/:-.`..:-/o:`-:-:::-/hho`` `..`  ` ``-.-+.   `               \n");
printf ("                         ``.``.....-:.:/:----..`-/.`:-----+hhy/````--. `` `.-.`/.   `               \n");
printf ("                         ``.`-:////+--/+//::-..``- -------sh:y/```.-..`````o-.`/.  ``               \n");
printf ("                           .`...--:/::////..`.`` ..:-----+y/./:```--.-.```-y:`./` ```               \n");
printf ("                           ``...--:////++/---.   .:-:----yo``````.--.`-.`.-y+.:-` ```               \n");
printf ("                         `  -...-:::////://:++```-:....:/h+-.....-...`.--:-os-.`` ```               \n");
printf ("                         ` -s:`.-:::-------/++:--:-`.-.-/ho......-`.``.-+:-/s.` `````               \n");
printf ("                         `.os+.:/+++:---::.+o//::--..-``.os-......````.-y--:s-`  ```                \n");
printf ("                ``   ` ` .osso:://:--:/+oso++/+/----..```-:--....`````.os-.-o: ```                  \n");
printf ("                ```  `  `+osoo/---::///+hh+++/+/--...````..`.--:`````.:y+..-o/ ` `  `               \n");
printf ("                ``    ``/os+/-.....-/:::dd++///:.//:...```.``.---```..ss:..-o+ ` `  `               \n");
printf ("                 `   ` -++:-.....```::::dmo//:/:.::::-..``..````--.../yo-.`-o/ ` `  `               \n");
printf ("                 `  ```//.......````----dms//::-`-:-::-..``..```.--.-so/-.`:o:     `                \n");
printf ("                `   ` .+-`.....`````....hms/:--. ----:-:o:...````-.-/o+:.``/+-  `  ``               \n");
printf ("                `   ``-/.``````````-````sms/---. .------hmo--....--:o+/-.``+/``    ``               \n");
printf ("                `   ` -/``````` ``.```` ohs/-.-. .------yNo---::--:++/:-``-+: ```  ``               \n");
printf ("                `   ```/.```````````    shs/---. .-----.sm/....---////:-``:/`` `   ``               \n");
printf ("                     ` ..````` `````    ohs/---. ------.sd/...``..://::.`.+.`                       \n");
printf ("                      ` ```    `.````   /hyo/--. ------:yd/```````.//::.`-.``                       \n");
printf ("                         ``  ``..````````/oyy+:. :-:/+oyh+.```` ```-/::````                         \n");
printf ("    `````                ``  `....`````````-oyy/:osyys+:.``     ```-:::`  ```                       \n");
printf ("  ``````                 `   ```...``````````-oyhdy/.`` ``` ````.....:/``                           \n");
printf ("  ``````                 ` ` .``````````-:.````-+yhyo.```````.....```./.``                          \n");

printf ("                                                    mmNNNNNNmmN                                     \n");
printf ("                                               NNmmmmdddddddmdmNN                                   \n");
printf ("                                            NmmmdddddddddddddddmddmNN                               \n");
printf ("                                           Nmmdddddmmmdddddddddddddddm                              \n");
printf ("                                      NN NmmmhddhmmmddddddddhddmhdmddhdN                            \n");
printf ("                                       NmmdmhddhmmmddhhdddhdhhmmdhmmdhhdmNN                         \n");
printf ("                                       NmdddydddmmdhdhhhhhhddymmdddmmdhhdmN                         \n");
printf ("                                      NmmddhydddmmhdhhhyydhddhmmdmdmmmddddN                         \n");
printf ("                                     NmmddddddddmdmdydyyddhmmdmmmmmdmmdddddN                        \n");
printf ("                                     mNmddddddmmdmmhdhhddddmmmmmmmmmmmmddddmNN                      \n");
printf ("                                    NNmmmmmmmmddmmdddddmmmmmmdmmmdmmmmmmddmm                        \n");
printf ("                                    NmmmmdmmddddmmddddmmmmmddmmdmmmmdddmddmmN                       \n");
printf ("                                    mmNmmmmmmmdmmmmmmmmmmmdmmmdomsymmddmmmmmm                       \n");
printf ("                                    mNNmmmmmmdmmddmmdymmmmmmmy+oh/:ymdmmmmmNN                       \n");
printf ("                                    m NmmmmmdohddhmdyymmmmmdysydyssodmmmmmNN                        \n");
printf ("                                     NNmmdmmd:yyhdhdshmmddo::shhhyyohmddmN                          \n");
printf ("                                        myddho:oos+:+dd+/o-..:-:oo+/ddyd                            \n");
printf ("                                       Nmmysy:-....:/y+.--.........odod                             \n");
printf ("                                       NNNmhso.......:/--..........oshN                             \n");
printf ("                                          Nmmd:.......-++........./dmm                              \n");
printf ("                                            Nmd/.......//-.......:dmmN                              \n");
printf ("                                            mmmms-...::://::-...+dmmN                               \n");
printf ("                                           N Nmmd++-...-/-...-/ommm                                 \n");
printf ("                                              NNm+/++/-....-+o+sN N                                 \n");
printf ("                                               Nm//+/++++++o+/:omN                                  \n");
printf ("                                              Nmd/--::::::::-..ymmm                                 \n");
printf ("                                            Nmmms:.`.-::::-.``.sdmmmN                               \n");
printf ("                                          Nmmmdm/-````....`````.dddmmmmN                            \n");
printf ("                                      NNmmmmmddm+:..``````````:smdddmmddmmNN                        \n");
printf ("                                NNNmmmmddmmddddmo///::---..-:/+ddddddmmddddmmmmNN                   \n");
printf ("                           NNmmmmmddddddmmddddmms`...-:-.-:-..smmdddddmmdddddddmmmmNN               \n");
printf ("                       Nmmmmmddddddddddmmddddmmdy.```````````:mdmmddddmmddddddddddddmmmmN           \n");
printf ("                      Nmddmddddddddddmmmddddmmddd.``````````-hdddmmmdddmmdddddddddddmmddm           \n");
printf ("                      mdddmmdddddddddmdddddmmdddd/`````````.smdddddmmmddmmddddddddddmmddmN          \n");
printf ("                     Nmdddmmddddddddmmmmmmmmddddms`````````/dddddddmmmmmmmddddddddddmmddmN          \n");
printf ("                     Nmddddmdddmmddddmmmmmdddddddh.```````-ddddddddmddmmmddddddddddmmddddm          \n");
printf ("                     mdddddmmddmmddddmmddddddddddd:``````.smdddddddmdmmmmdddddmmdddmmddddm          \n");
printf ("                     mddddddmddmmdddddmmmddddddddmo.````.+dddddddddddmmmddddddmmdddmdddddmN         \n");
printf ("                     mddddddmmdmmdddddddmmmdddddddh-````:ddddddddddmmmddddddddmmddmmdddddmN         \n");
printf ("                    Nmddddddmmdmmddddddddmmmddddddm+```-hddddddddmmmddddddddddmmddmmdddddmN         \n");
printf ("                    Nmdddddddmmmmdddddddddmmmmdddddh.`.ymddddddmmmmmmmmmmmmmddmmdmmdddddddm         \n");
printf ("                    Nmdddddddmmmmdddddddddddmmmmdddm+.sddddddmmmmmmddddddddmddmmmmmdddddddm         \n");
printf ("                    Nmdddddddmmmmddddddddddddmmmmmdddymddddmmmmdsyysossoyddmddmmmmddddddddm         \n");
printf ("                    Nmdddddddmmmmdddddddddddddmmmmmmmmdddmmmmmdy/.-::---oddmddmmmmddddddddmN        \n");
printf ("                    Nmddddddddmmmdddddddddddddddmmmmmdddmmmmmmddo//////+yddmddmmmmmmddddddmN        \n");
printf ("                    Nmddddddddmmmddddddddddddddddmmmddmmmmddmdyyo//////+osymdddmmdmddddddddm        \n");
printf ("                    mmddddddddmmmddddddddddddddddmmdmmmmmdddmdysy+/:.:/oyshmdddmmmmddddddddm        \n");
printf ("                    mdddddddddmmdddddmddddddddddmmdmddddddddmmddhyyo+oyyhddmdddmmmmddddddddmN       \n");

printf ("                                       N NNNmmNNm                                                   \n");
printf ("                                       NhhddddddddmN                                                \n");
printf ("                                     mmhyhhddddmmmmmm                                               \n");
printf ("                                     mhhhyhhddddddddd                                               \n");
printf ("                                     Nhdhddddddmmdddd                                               \n");
printf ("                                     NmdhmmhdhdmmmmmmN                                              \n");
printf ("                                      Nmhh:-:/+shshy                                                \n");
printf ("                                       Nm+....-::+Noh                                               \n");
printf ("                                        m`.--:+oss+s-N                                              \n");
printf ("                                      Ndho.`-/sho+:.-+N                                             \n");
printf ("                                  NNmhhddmh:.:/hoh/.--+N                                            \n");
printf ("                                ddddhhddmmmd+--oddds:--sm                                           \n");
printf ("                                shdddmdddmmmms-+mmmdyssydm                                          \n");
printf ("                                shddmNmddddmmmy+mmmhdmddmm                                          \n");
printf ("                                dhhdmmNmdddddmmdmmdoymmhmmm                                         \n");
printf ("                                 yhddmmNmdddddmmddmhymmmmmm                                         \n");
printf ("                                 mhhdmmNmmdddddmmmmmmNmmmmmm                                        \n");
printf ("                                  yhhdmmNmmddddmmmmmNNmmmmmdN                                       \n");
printf ("                                  yhhdmmmddddddmmhdmmNmmNmmmm                                       \n");
printf ("                                  hhdddddddddddddddddmmms++sod                                      \n");
printf ("                                  Nddmdmmmmmmmddmmmmmmmd+/+osm                                      \n");
printf ("                                    Nmhdmmmmmmmmmmmmmmmdhyhm                                        \n");
printf ("                                     NshdmmmmmmmNNmNNmd                                             \n");
printf ("                                     mshhddddddmmmmmmmdN                                            \n");
printf ("                                    Nyyhhdddddddmmmdmmdd                                            \n");
printf ("                                    msyhhdddddddmmmhmmmh                                            \n");
printf ("                                    hyhhhdddddddmmmmmmmdm                                           \n");
printf ("                                   Nsyhhdhhdddddmmmmmmmdd                                           \n");
printf ("                                   hshhhhddddddmmmmmmmmddm                                          \n");
printf ("                                   shhhhdddddddmmmmmmmmmdd                                          \n");
printf ("                                  mshhdddddddmmmmmmmmmmmddm                                         \n");
printf ("                                  dhddhddhhmmddmmmmNmmmmmmm                                         \n");
printf ("                                  NNdyyhyhshhhdmdmmmddddh                                           \n");
printf ("                                   mosddydhmddNmmNNmddmdd                                           \n");
printf ("                                   oooyysshdhN ddmmddddhd                                           \n");
printf ("                                  N+ohdydsmdd  hdmmddddhm                                           \n");
printf ("                                  y+oyssshdd   yhdmddhdyd                                           \n");
printf ("                                  ooyhyhsdhN   hddmmhhdym                                           \n");
printf ("                                 mooyssshdm    hhhddhhhyN                                           \n");
printf ("                                 sosysyydd     dhdmmhhdy                                            \n");
printf ("                                Nooyosohd      myhddhyhh                                            \n");
printf ("                                hsyhsshdN      Nyhmmdhdh                                            \n");
printf ("                                ysyooshm       Nyyhdhyyd                                            \n");
printf ("                               dsyysohd        Nshdmhhdm                                            \n");
printf ("                               ssyssydm        NsyhdyyyN                                            \n");
printf ("                              Nsyhyshd         Nsyddhhd                                             \n");
printf ("                              yohyyhdN         msydhhhd                                             \n");
printf ("                             msyysshd          dyhdhhdd                                             \n");
printf ("                             sshyyhdN          dyhmdhdd                                             \n");

int position=1;
    int keypressed=0;
    #define MAX 5
    #define MIN 1

    while(keypressed!=13)
    {
    system("cls");
    color(0);
    printf("\t\t\t\t                                                          ...`..-:/:.  ````                                   \n");
    printf("\t\t\t\t                                                      .:omNNNNNNNMMMNmmmNNmmy/`                               \n");
    printf("\t\t\t\t                                                    -hNMMMMMMMMMMMMMMMMMMMMMMMmo`                             \n");
    printf("\t\t\t\t                                                  :yNMMMMMMMMMMMMMMMMMMMMMMMMMMMm/`                           \n");
    printf("\t\t\t\t                                                 /NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd-                          \n");
    printf("\t\t\t\t                                                `:yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs.                        \n");
    printf("\t\t\t\t                                  ``````          /NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd`                       \n");
    printf("\t\t\t\t                            `-+hddmddhs+`         +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:                       \n");
    printf("\t\t\t\t                       `:ohdmNMMMMMMMMMNy/        +NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN.                       \n");
    printf("\t\t\t\t                     `:hNMMMMMMMMMMMMMMMMNo`      yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh                        \n");
    printf("\t\t\t\t         `:ohmmmmo+dMMMMMMMMMMMMMMMMMMMMMMMNs.     :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd`                        \n");
    printf("\t\t\t\t        /dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd`    oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo                         \n");
    printf("\t\t\t\t        yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN-   .mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy`                        \n");
    printf("\t\t\t\t        -NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd:` sNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh`                        \n");
    printf("\t\t\t\t        yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdo+/:mMMMMMMMMMMMMMMMMMMMMMMMMMMMMms.                         \n");
    printf("\t\t\t\t        hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd-`yNMMMMMMMMMMMMMMMMMMMMMMMMMMd.                           \n");
    printf("\t\t\t\t        -hNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo  `+hMMMMMMMMMMMMMMMMMMMMMMMMNh-                           \n");
    printf("\t\t\t\t         `-+NMMMMmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm-   oNMMMMMMMMMMMMMMMMMMMMMMMy`                            \n");
    printf("\t\t\t\t            +hdds/NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN-   :dNMNmmdyssmMMMMMMMMMMMMMy`                            \n");
    printf("\t\t\t\t             ``` -NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN+    .-:-.``   /NMMMMMMMMMMMMNh:                           \n");
    printf("\t\t\t\t                 `dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNd+              /MMMMMMMMMMMMMMMm:                          \n");
    printf("\t\t\t\t                  :dMMMMMMMMMMMMMMMMMMMMMMMMdso/-.`               oNMMMMMMMMMMMMMMMm+.                        \n");
    printf("\t\t\t\t                   ./o+ohmmdhhoodMMMMMMMMMMs`                     -mMMMMMMMMMMMMMMMMMd-                       \n");
    printf("\t\t\t\t                         `.`:```+NMMMMMMMMd`                    .smMMMMMMMMMMMMMMMMMMMm:                      \n");
    printf("\t\t\t\t                           .``  +NMMMMMMMN/                    `dMMMMMMMMMMMMMMMMMMMMMMN+                     \n");
    printf("\t\t\t\t                         ``    `yMMMMMMMMm`                    :NMMMMMMMMMMMMMMMMMMMMMMMN+                    \n");
    printf("\t\t\t\t                              `oNMMMMMMMMh                    .yMMMMMMMMMMMMMMMMMMMMMMMMMN:                   \n");
    printf("\t\t\t\t                              oNMMMMMMMMMN-                  :dMMMMMMMMMMMMMMMMMMMMMMMMMMMd`                  \n");
    printf("\t\t\t\t                             +NMMMMMMMMMMMd`                :mMMMMMMMMMMMMMMMMMMMMMMMMMMMMN+                  \n");
    printf("\t\t\t\t                          `/yNMMMMMMMMMMMMMo               .dMMMMMMMMMMMMMMMMMMMMMMMMMMNmds/                  \n");
    printf("\t\t\t\t                          .ymMMMMMMMMMMMMMMN-              sMMMMMMMMMMMMMMMMMMMMMMMMNdo:`                     \n");
    printf("\t\t\t\t                            ./yNMMMMMMMMMMMMh`            .mMMMMMMMMMMMMMMMMMMMMMNdo-                         \n");
    printf("\t\t\t\t                               .+dNMMMMMMMMMMd:`          +MMMMMMMMMMMMMMMMMMMMms:                            \n");
    printf("\t\t\t\t                                  -odNMMMMMMMMMNy.        hMMMMMMMMMMMMMMMMMmy/`                              \n\n\n");
    color(4);
    printf("\t\t\t\t\t\t\t\t\tSHOP\n");
    printf("\t\t\t\t\t\t\t\tYour Money is %d\n",uang[0]);
    arrowhere(1,position);printf("Ferdian 1 (money-=500)\n");
    arrowhere(2,position);printf("Ferdian 2 (money-=1000)\n");
    arrowhere(3,position);printf("lily 2 (money-=1000)\n");
    arrowhere(4,position);printf("GALLERY\n");
    arrowhere(5,position);printf("Main Menu\n");

    keypressed=getch();
    if(keypressed==80&&position!=MAX)
    {
        position++;
    }
    else if(keypressed==72&&position!=MIN)
    {
        position--;
    }
    else
    {
        position==position;
    }
    }
}
